// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx2sA5Zw6SOXYC44IpBWPljKHGWNy4ywM',
    appId: '1:922813966919:web:29fa19939fb64061b29f62',
    messagingSenderId: '922813966919',
    projectId: 'udit-assesment',
    authDomain: 'udit-assesment.firebaseapp.com',
    storageBucket: 'udit-assesment.appspot.com',
    measurementId: 'G-RC14SQ8SJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBKKu10NOJeDFej2cc5bJ13XQCa0zOitM',
    appId: '1:922813966919:android:7ec92cf12e4b3076b29f62',
    messagingSenderId: '922813966919',
    projectId: 'udit-assesment',
    storageBucket: 'udit-assesment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHoE4x-u7FrfCfPyjDKgxzhWe4ppVXkxk',
    appId: '1:922813966919:ios:45a2b4b8217e63b5b29f62',
    messagingSenderId: '922813966919',
    projectId: 'udit-assesment',
    storageBucket: 'udit-assesment.appspot.com',
    iosBundleId: 'com.example.uditAssesment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx2sA5Zw6SOXYC44IpBWPljKHGWNy4ywM',
    appId: '1:922813966919:web:18a89fa3101ff5a0b29f62',
    messagingSenderId: '922813966919',
    projectId: 'udit-assesment',
    authDomain: 'udit-assesment.firebaseapp.com',
    storageBucket: 'udit-assesment.appspot.com',
    measurementId: 'G-K4HBYY02R7',
  );

}